// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9kAcjuwfnlUR9y6m4DT1ulyEITegvfCo',
    appId: '1:1031981180165:web:2e3b392397f8052b9e836c',
    messagingSenderId: '1031981180165',
    projectId: 'walkistry',
    authDomain: 'walkistry.firebaseapp.com',
    storageBucket: 'walkistry.appspot.com',
    measurementId: 'G-NLF3DKS1JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9_d_c51n3hQKvxF5KLjpRKHO-xMnsBwI',
    appId: '1:1031981180165:android:9940c1b0ebfcb5669e836c',
    messagingSenderId: '1031981180165',
    projectId: 'walkistry',
    storageBucket: 'walkistry.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-ljf9XcQRhTwgkKyx3hHqWSxsVmtuySk',
    appId: '1:1031981180165:ios:332d6af26f4497d29e836c',
    messagingSenderId: '1031981180165',
    projectId: 'walkistry',
    storageBucket: 'walkistry.appspot.com',
    androidClientId: '1031981180165-7jsqnv7tcn51e96nf0q1h19mt7dhtfvr.apps.googleusercontent.com',
    iosClientId: '1031981180165-rua7n5t7i1c54453feo0om17po12eprn.apps.googleusercontent.com',
    iosBundleId: 'com.walkistry.project',
  );
}
